// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BlazorApp.Data
{
    public partial class Employee
    {
        public int Id { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string Department { get; set; }

        [Required]
        public DateTime? EntryDate { get; set; }

        [Required]
        public string Tasks { get; set; }

        public bool IsArchived { get; set; }
    }
}